'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''rd_Record_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd_Record_New As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd_Record_Exists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd_Record_Exists As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''pn_Periph_Select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_Periph_Select As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_Device control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Device As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drp_Device control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_Device As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pn_OrderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_OrderID As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tbl_Order_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_Order_ID As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lbl_Order_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Order_ID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_Order_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Order_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_Retrieve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Retrieve As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbl_Equipment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_Equipment As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lbl_ItemDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ItemDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_ItemDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ItemDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_SerialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_SerialNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_SerialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SerialNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_HelpDeskNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_HelpDeskNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_HelpDeskNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_HelpDeskNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_StateNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_StateNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_StateNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_StateNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_ITNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ITNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_ITNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ITNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drp_Month control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_Month As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drp_Day control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_Day As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drp_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_Year As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_ValidDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ValidDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_DevType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_DevType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drp_DevType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_DevType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pn_EnterType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_EnterType As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_EnterType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_EnterType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_EnterType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_EnterType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_Notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Notes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_Notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Notes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chk_Return control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_Return As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tbl_Periphs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_Periphs As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''pn_Periph_Rem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_Periph_Rem As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btn_Periph_Rem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Periph_Rem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pn_Periph_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_Periph_Add As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btn_Periph_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Periph_Add As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tbl_personinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_personinfo As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lbl_FName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_FName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_FName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_FName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_LName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_LName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_LName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drp_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_Type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pn_NewHire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_NewHire As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_NewHire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_NewHire As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rd_NewHireY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd_NewHireY As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rd_NewHireN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd_NewHireN As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lbl_PhoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_PhoneNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_PhoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PhoneNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Email As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pn_CollegeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_CollegeID As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tbl_CollegeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_CollegeID As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lbl_CollegeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CollegeID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_CollegeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CollegeID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pn_CCAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_CCAuth As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tbl_CCAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_CCAuth As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lbl_CCAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_CCAuth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chk_CCAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_CCAuth As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pn_Signatures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_Signatures As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tbl_Signatures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_Signatures As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''pn_UserSign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_UserSign As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_UserSign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_UserSign As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_UserSign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_UserSign As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pn_AuthBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_AuthBy As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_AuthBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_AuthBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_AuthBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_AuthBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pn_FTAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_FTAuth As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_FTAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_FTAuth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_FTAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_FTAuth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pn_Returns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_Returns As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tbl_Returns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_Returns As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''lbl_ReturnStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ReturnStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drp_ReturnStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_ReturnStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pn_EULA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_EULA As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pn_facEULA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_facEULA As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pn_studEULA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_studEULA As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chk_EULAread control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_EULAread As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btn_Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Submit As Global.System.Web.UI.WebControls.Button
End Class
