'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1

    '''<summary>
    '''tbl_Filters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl_Filters As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''pn_Tables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_Tables As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_Tables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Tables As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drp_Tables control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_Tables As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pn_FilterBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_FilterBy As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_FilterBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_FilterBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drp_FilterBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_FilterBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pn_DateFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_DateFilter As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_DateFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_DateFilter As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drp_MonthFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_MonthFilter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drp_DayFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_DayFilter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drp_YearFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_YearFilter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pn_TextFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pn_TextFilter As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_TextFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_TextFilter As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_TextFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_TextFilter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_Filter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Filter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grd_Data control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_Data As Global.System.Web.UI.WebControls.GridView
End Class
